(function (root) {
  "use strict";
  const bridge = (root.WebLLMBridge = root.WebLLMBridge || {});
  bridge.createContentRuntime = function createContentRuntime(providerId) {
    const provider = bridge.getProvider(providerId);
    if (!provider) throw new Error(`未注册 Provider：${providerId}`);
    const timing = { ...(provider.timing || {}), ...(bridge.timing || {}) };
    const adapter = provider.adapter;
    const history = bridge.createHistory(provider, timing);
    let revision = 0; let scheduled = false;
    const traces = new Map(); const traceOrder = []; const MAX_TRACE_EVENTS = 128; const MAX_TRACE_REQUESTS = 16;
    function traceEvent(requestId, phase, startedAt, data = {}) {
      if (typeof requestId !== "string" || !requestId) return;
      let trace = traces.get(requestId);
      if (!trace) { trace = { request_id: requestId, started_at: startedAt, events: [] }; traces.set(requestId, trace); traceOrder.push(requestId); while (traceOrder.length > MAX_TRACE_REQUESTS) traces.delete(traceOrder.shift()); }
      const event = { phase, elapsed_ms: Math.max(0, Math.round(root.performance.now() - startedAt)) };
      for (const [key, value] of Object.entries(data)) { if (value !== undefined) event[key] = value; }
      trace.events.push(event); if (trace.events.length > MAX_TRACE_EVENTS) trace.events.splice(0, trace.events.length - MAX_TRACE_EVENTS);
    }
    function traceArtifact(item) { return { id: item?.id || "", index: Number.isInteger(item?.index) ? item.index : null, ready: item?.ready === true, complete: item?.complete === true, width: item?.width ?? null, height: item?.height ?? null, natural_width: Number(item?.naturalWidth || 0), natural_height: Number(item?.naturalHeight || 0), source_kind: item?._source_kind || null }; }
    function traceSnapshot(requestId) { const trace = traces.get(requestId); if (!trace) throw bridge.error("DEBUG_TRACE_NOT_FOUND", "找不到指定的调试 Trace", true); return { request_id: requestId, events: trace.events.map((event) => ({ ...event })) }; }
    function traceExternal(requestId, phase) { const trace = traces.get(requestId); if (trace) traceEvent(requestId, phase, trace.started_at); }
    function traceSubmitted(requestId, startedAt) { traceEvent(requestId, "submitted", startedAt); }
    function promptText(prompt) { return typeof prompt?.value === "string" ? prompt.value : prompt?.innerText || ""; }
    function input(prompt, text) { prompt.dispatchEvent(new InputEvent("input", { bubbles: true, inputType: "insertText", data: text })); }
    function write(prompt, text) {
      if (prompt.isContentEditable) {
        prompt.focus(); const range = document.createRange(); range.selectNodeContents(prompt); const selection = root.getSelection(); selection.removeAllRanges(); selection.addRange(range);
        if (!document.execCommand("delete", false)) { range.deleteContents(); input(prompt, ""); }
        if (!document.execCommand("insertText", false, text)) { range.selectNodeContents(prompt); range.deleteContents(); range.insertNode(document.createTextNode(text)); input(prompt, text); }
      } else if ("value" in prompt) { const descriptor = Object.getOwnPropertyDescriptor(Object.getPrototypeOf(prompt), "value"); if (descriptor?.set) descriptor.set.call(prompt, ""); else prompt.value = ""; if (descriptor?.set) descriptor.set.call(prompt, text); else prompt.value = text; input(prompt, text); }
      else throw bridge.error("INPUT_FAILED", "输入框不支持文本写入");
      if (bridge.normalizeText(promptText(prompt)) !== bridge.normalizeText(text)) throw bridge.error("INPUT_FAILED", "文本未成功写入输入框");
    }
    async function waitFor(find, code, message, timeout) { const deadline = root.performance.now() + timeout; while (root.performance.now() < deadline) { const value = find(); if (value) return value; await bridge.sleep(timing.pollIntervalMs); } throw bridge.error(code, message); }
    async function sendText(text) {
      if (adapter.isGenerating()) throw bridge.error("BUSY", "页面当前仍在生成回复");
      const deadline = root.performance.now() + timing.pageReadyTimeoutMs; let lastError;
      while (root.performance.now() < deadline) { try { const remaining = Math.max(1, deadline - root.performance.now()); const prompt = await waitFor(adapter.findPrompt, "PROMPT_NOT_FOUND", "页面仍在加载，输入框尚未就绪", remaining); write(prompt, text); const button = await waitFor(() => { const candidate = adapter.findSendButton(); return candidate && adapter.isEnabled(candidate) ? candidate : null; }, "SEND_BUTTON_NOT_FOUND", "发送按钮不可用或页面结构发生变化", Math.min(remaining, timing.buttonReadyTimeoutMs)); button.click(); return; } catch (error) { lastError = error; if (!["PROMPT_NOT_FOUND", "SEND_BUTTON_NOT_FOUND", "INPUT_FAILED"].includes(error?.code)) throw error; await bridge.sleep(timing.pollIntervalMs); } }
      throw bridge.error("PAGE_NOT_READY", lastError ? "页面在限定时间内未完成加载，输入框或发送按钮仍不可用" : "页面在限定时间内未完成加载");
    }
    function progress(requestId, phase, startedAt, activityAt) { if (typeof requestId !== "string" || !requestId) return; const now = root.performance.now(); try { const result = chrome.runtime.sendMessage({ type: "chat_progress", request_id: requestId, phase, elapsed_ms: Math.max(0, Math.round(now - startedAt)), idle_ms: Math.max(0, Math.round(now - activityAt)) }); result?.catch?.(() => {}); } catch (_error) {} }
    async function waitForSubmitted(beforeUsers, text, baseline, requestId, startedAt) {
      const deadline = root.performance.now() + timing.submissionConfirmationTimeoutMs; let lastRevision = revision; let lastProgress = startedAt; let lastActivity = startedAt; progress(requestId, "working", startedAt, lastActivity);
      while (root.performance.now() < deadline) { if (adapter.getUsers().length > beforeUsers) { traceSubmitted(requestId, startedAt); return; } const prompt = adapter.findPrompt(); if ((prompt && bridge.normalizeText(promptText(prompt)) === "") || adapter.isGenerating() || (adapter.getLastAssistant() && adapter.getLastAssistant() !== baseline)) { traceSubmitted(requestId, startedAt); return; } const now = root.performance.now(); if (revision !== lastRevision) { lastRevision = revision; lastActivity = now; } if (now - lastProgress >= timing.progressIntervalMs) { progress(requestId, "working", startedAt, lastActivity); lastProgress = now; } await bridge.sleep(timing.pollIntervalMs); }
      throw bridge.error("SEND_FAILED", "页面在 60 秒内未确认消息提交，可能仍在加载");
    }
    async function waitForComplete(requestId, baseline, startedAt) {
      const baselineText = (baseline?.innerText || "").trim(); let lastActivity = startedAt; let lastRevision = revision; let lastText = baselineText || null; let lastNode = baseline; let lastArtifactSignature = ""; let lastReadySignature = ""; let stableSince = null; let lastProgress = startedAt; let lastPhase = "thinking"; let observed = false; let kind = "thinking"; let snapshot = adapter.activitySnapshot(); let marker = adapter.hasCompletionMarker(baseline); let candidateSince = null; let serialized = null; progress(requestId, "thinking", startedAt, lastActivity);
      while (true) { const now = root.performance.now(); const assistant = adapter.getLastAssistant(); const current = (assistant?.innerText || "").trim(); const artifacts = assistant && adapter.getArtifacts ? adapter.getArtifacts(assistant) : []; const artifactSignature = JSON.stringify(artifacts.map((item) => [item.id, item.source_identity, item.width, item.height, item.complete, item.naturalWidth, item.naturalHeight, item.ready])); const artifactChanged = artifactSignature !== lastArtifactSignature; const nextSnapshot = adapter.activitySnapshot(); const nextMarker = adapter.hasCompletionMarker(assistant); const markerChanged = nextMarker !== marker; const changed = revision !== lastRevision || current !== lastText || artifactChanged || nextSnapshot.signature !== snapshot.signature || markerChanged;
        if (changed) { lastActivity = now; lastRevision = revision; observed = true; kind = nextSnapshot.toolCall ? "tool_call" : "working"; } snapshot = nextSnapshot; marker = nextMarker; const nodeChanged = assistant !== lastNode; if (nodeChanged) { lastNode = assistant; candidateSince = null; serialized = null; lastArtifactSignature = ""; } if (current !== lastText || artifactChanged || nodeChanged) { lastText = current; lastArtifactSignature = artifactSignature; stableSince = now; }
        if (nodeChanged && assistant && assistant !== baseline) { lastReadySignature = ""; const snapshot = adapter.debugSnapshot ? adapter.debugSnapshot(revision) : null; traceEvent(requestId, "assistant_node_seen", startedAt, { turn_id: snapshot?.assistant?.turn_id || null, text_length: current.length, text_hash: snapshot?.assistant?.text_hash || null, artifact_count: artifacts.length }); }
        if (artifactChanged && artifacts.length) traceEvent(requestId, "artifact_seen", startedAt, { artifacts: artifacts.map(traceArtifact), signature: artifactSignature });
        const newReplyObserved = Boolean(assistant && (assistant !== baseline || current !== baselineText)); const responseExists = newReplyObserved && Boolean(current || artifacts.length); const artifactsReady = artifacts.length > 0 && artifacts.every((item) => item.ready === true); const readySignature = artifactsReady ? artifactSignature : ""; if (readySignature && readySignature !== lastReadySignature) { lastReadySignature = readySignature; traceEvent(requestId, "artifact_ready", startedAt, { artifacts: artifacts.map(traceArtifact) }); } if (!adapter.isGenerating() && responseExists && assistant && (current || artifactsReady)) { const next = bridge.serializeMessageToMarkdown(assistant, adapter.serializer); if (markerChanged || artifactChanged) { candidateSince = null; serialized = null; } if (serialized !== next) { if (serialized !== null) { lastActivity = now; stableSince = now; observed = true; } serialized = next; candidateSince = now; traceEvent(requestId, "completion_candidate", startedAt, { text_length: next.length, artifact_count: artifacts.length }); } else if (candidateSince === null) { candidateSince = now; traceEvent(requestId, "completion_candidate", startedAt, { text_length: next.length, artifact_count: artifacts.length }); } } else { candidateSince = null; serialized = null; }
        const phase = current ? "streaming" : kind === "tool_call" && now - lastActivity <= timing.progressIntervalMs ? "tool_call" : observed && now - lastActivity <= timing.progressIntervalMs ? "working" : "thinking"; if (phase !== lastPhase || now - lastProgress >= timing.progressIntervalMs) { progress(requestId, phase, startedAt, lastActivity); lastPhase = phase; lastProgress = now; }
        if (responseExists && (!artifacts.length || artifactsReady) && stableSince !== null && now - stableSince >= timing.stableTimeMs && now - lastActivity >= timing.stableTimeMs && candidateSince !== null && now - candidateSince >= timing.completionConfirmationMs && !adapter.isGenerating()) { const final = adapter.getLastAssistant(); const finalText = final && bridge.serializeMessageToMarkdown(final, adapter.serializer); const finalArtifacts = final && adapter.getArtifacts ? adapter.getArtifacts(final) : []; if (finalText === serialized && (!finalArtifacts.length || finalArtifacts.every((item) => item.ready === true))) { traceEvent(requestId, "completed", startedAt, { text_length: (finalText || "").length, artifact_count: finalArtifacts.length }); return { text: finalText || "", artifacts: finalArtifacts }; } candidateSince = null; serialized = null; stableSince = null; }
        if (now - lastActivity >= timing.responseIdleTimeoutMs) throw bridge.error("RESPONSE_TIMEOUT", "连续 5 分钟未检测到页面更新，可能仍在思考或页面结构已变化"); await bridge.sleep(timing.pollIntervalMs);
      }
    }
    async function sendArtifactChunks(artifact, requestId) { const source = artifact?.source || artifact?._source; if (!source || typeof root.fetch !== "function") throw bridge.error("ARTIFACT_UNAVAILABLE", "Artifact 来源不可用"); let response; try { response = await root.fetch(source); } catch (error) { throw bridge.error("ARTIFACT_TRANSFER_FAILED", error?.message || "无法读取 Artifact"); } if (!response?.ok) throw bridge.error("ARTIFACT_TRANSFER_FAILED", "无法读取 Artifact"); const buffer = await response.arrayBuffer(); const bytes = new Uint8Array(buffer); const mimeType = response.headers?.get?.("content-type") || artifact.mime_type || ""; const chunkSize = 256 * 1024; const send = async (message) => { const result = chrome.runtime.sendMessage({ ...message, request_id: requestId }); await result?.catch?.(() => {}); }; await send({ type: "artifact_start", artifact_id: artifact.id, mime_type: mimeType, size: bytes.byteLength }); for (let offset = 0, sequence = 0; offset < bytes.length; offset += chunkSize, sequence += 1) { let binary = ""; for (const value of bytes.subarray(offset, Math.min(bytes.length, offset + chunkSize))) binary += String.fromCharCode(value); await send({ type: "artifact_chunk", artifact_id: artifact.id, sequence, data: root.btoa(binary) }); } await send({ type: "artifact_end", artifact_id: artifact.id }); return { transferred: true, size: bytes.byteLength, mime_type: mimeType };
    }
    async function waitForArtifact(message) { const timeout = Number.isFinite(message?.timeout_ms) ? Math.max(1_000, Math.min(300_000, Number(message.timeout_ms))) : 60_000; const deadline = root.performance.now() + timeout; let last = null; while (root.performance.now() < deadline) { try { last = adapter.resolveArtifact({ artifact_id: message?.artifact_id, turn_id: message?.turn_id, index: message?.index }); if (last?.ready === true) return last; } catch (error) { if (error?.code !== "ARTIFACT_NOT_FOUND") throw error; } await bridge.sleep(timing.pollIntervalMs); } if (last) throw bridge.error("ARTIFACT_NOT_READY", "Artifact 尚未就绪", true); throw bridge.error("ARTIFACT_NOT_READY", "在限定时间内未找到指定 Artifact", true); }
    async function chat(text, requestId) { if (typeof text !== "string" || !text.trim()) throw bridge.error("INPUT_FAILED", "消息不能为空"); const beforeUsers = adapter.getUsers().length; const baseline = adapter.getLastAssistant(); const started = root.performance.now(); const snapshot = adapter.debugSnapshot ? adapter.debugSnapshot(revision) : null; traceEvent(requestId, "before_send", started, { user_count: snapshot?.counts?.users ?? beforeUsers, assistant_count: snapshot?.counts?.assistants ?? 0, generating: snapshot?.generating === true }); try { progress(requestId, "working", started, started); await sendText(text); await waitForSubmitted(beforeUsers, text, baseline, requestId, started); progress(requestId, "submitted", started, started); return await waitForComplete(requestId, baseline, started); } catch (error) { if (["CHAT_STATE_UNKNOWN", "EXTENSION_NOT_CONNECTED", "CONTENT_SCRIPT_UNAVAILABLE", "TAB_CLOSED"].includes(error?.code)) traceEvent(requestId, "chat_state_unknown", started, {}); throw error; } }
    function observe() { if (!document.body) return; new MutationObserver((records) => { if (records.some((record) => [...record.addedNodes, ...record.removedNodes, record.target].some((node) => adapter.isActivitySubtree(node?.nodeType === Node.ELEMENT_NODE ? node : node?.parentElement)))) revision += 1; if (!scheduled) { scheduled = true; root.setTimeout(() => { scheduled = false; history.capture({ prepend: history.active }); }, 100); } }).observe(document.body, { subtree: true, childList: true, characterData: true, attributes: true }); }
    observe();
    return { async handle(message) { if (message.method === "ping") return { ready: true, provider: provider.id }; if (message.method === "get_messages") return history.collect({ limit: message.limit, full: message.full === true }); if (message.method === "chat") return chat(message.text, message.request_id); if (message.method === "debug_snapshot") return { snapshot: adapter.debugSnapshot ? adapter.debugSnapshot(revision) : { revision }, trace_ids: traceOrder.slice(-8), latest_trace_id: traceOrder[traceOrder.length - 1] || null }; if (message.method === "debug_trace") return { trace: traceSnapshot(message.request_id) }; if (message.method === "trace_event") { if (message.phase !== "chat_state_unknown") throw bridge.error("INVALID_ARGUMENT", "不支持的 Trace 事件"); traceExternal(message.request_id, message.phase); return { recorded: true }; } if (message.method === "wait_artifact") return waitForArtifact(message); if (message.method === "resolve_artifact") return adapter.resolveArtifact({ artifact_id: message.artifact_id, turn_id: message.turn_id, index: message.index }); if (message.method === "get_artifact") return sendArtifactChunks(message.artifact, message.request_id); throw bridge.error("INTERNAL_ERROR", `未知内容脚本方法：${message.method}`); } };
  };
})(globalThis);
