(function (root) {
  "use strict";
  const bridge = (root.WebLLMBridge = root.WebLLMBridge || {});
  bridge.createTabs = function createTabs(timing) {
    async function get(tabId) { if (!Number.isInteger(tabId)) throw bridge.error("TAB_CLOSED", "绑定的标签页不存在", true); try { return await chrome.tabs.get(tabId); } catch (_error) { throw bridge.error("TAB_CLOSED", "绑定的标签页已关闭", true); } }
    async function close(tabId) { if (!Number.isInteger(tabId)) throw bridge.error("TAB_CLOSED", "绑定的标签页不存在", true); try { await chrome.tabs.remove(tabId); } catch (error) { const message = String(error?.message || error || ""); if (/no tab|not found|不存在|已关闭/i.test(message)) return { tab_id: tabId, closed: true }; throw bridge.error("CONTENT_SCRIPT_UNAVAILABLE", "无法关闭绑定的标签页"); } return { tab_id: tabId, closed: true }; }
    async function waitForContent(tabId) { const deadline = Date.now() + timing.contentReadyTimeoutMs; while (Date.now() < deadline) { await get(tabId); try { const response = await chrome.tabs.sendMessage(tabId, { method: "ping" }); if (response?.ok && response.result?.ready) return; } catch (_error) {} await bridge.sleep(timing.contentRetryIntervalMs); } throw bridge.error("PAGE_NOT_READY", "内容脚本在限定时间内未就绪"); }
    async function attach(params) { const provider = bridge.getProvider(params?.provider); if (!provider) throw bridge.error("PROVIDER_NOT_FOUND", "未注册的 Provider"); const url = typeof params?.url === "string" ? params.url : provider.defaultUrl; if (typeof url !== "string" || !provider.matchesUrl(url)) throw bridge.error("INVALID_URL", "不支持的 Provider 地址"); const target = provider.normalizeUrl(url); const requested = params?.tab_id; if (params?.new !== true && Number.isInteger(requested)) { try { const tab = await chrome.tabs.get(requested); if (provider.matchesUrl(tab.url || "") && provider.normalizeUrl(tab.url) === target) { await waitForContent(tab.id); return { tab_id: tab.id, url: (await get(tab.id)).url || url, provider: provider.id }; } } catch (_error) {} }
      if (params?.new !== true && typeof chrome.tabs?.query === "function") { const tabs = await chrome.tabs.query({}); const match = tabs.find((tab) => Number.isInteger(tab.id) && provider.matchesUrl(tab.url || "") && provider.normalizeUrl(tab.url) === target); if (match?.id !== undefined) { await waitForContent(match.id); return { tab_id: match.id, url: (await get(match.id)).url || url, provider: provider.id }; } }
      const tab = await chrome.tabs.create({ url, active: true }); if (!tab.id) throw bridge.error("PAGE_NOT_READY", "无法创建标签页"); await waitForContent(tab.id); return { tab_id: tab.id, url: (await get(tab.id)).url || url, provider: provider.id };
    }
    async function request(method, params) { const tabId = params?.tab_id; const requested = bridge.getProvider(params?.provider); if (!requested) throw bridge.error("PROVIDER_NOT_FOUND", "未注册的 Provider"); const tab = await get(tabId); const provider = bridge.detectProvider(tab.url || ""); if (!provider || provider.id !== requested.id) throw bridge.error("INVALID_URL", "标签页与请求 Provider 不匹配"); await waitForContent(tabId); const dispatched = method === "chat"; try { const response = await chrome.tabs.sendMessage(tabId, { method, text: params?.text, limit: params?.limit, full: params?.full === true, request_id: params?.request_id, artifact_id: params?.artifact_id, turn_id: params?.turn_id, index: params?.index, timeout_ms: params?.timeout_ms, provider: provider.id }); if (!response?.ok) { const error = response?.error || {}; throw bridge.error(error.code || "CONTENT_SCRIPT_UNAVAILABLE", error.message || "内容脚本返回了无效响应"); } return { ...(response.result || {}), url: (await get(tabId)).url || "", provider: provider.id, tab_id: tabId, ...(method === "chat" && typeof params?.request_id === "string" ? { request_id: params.request_id } : {}) }; } catch (error) { const normalized = error?.code ? error : bridge.error("CONTENT_SCRIPT_UNAVAILABLE", "无法向内容脚本发送消息"); if (dispatched && ["TAB_CLOSED", "CONTENT_SCRIPT_UNAVAILABLE", "EXTENSION_NOT_CONNECTED"].includes(normalized.code)) { try { await chrome.tabs.sendMessage(tabId, { method: "trace_event", request_id: params?.request_id, phase: "chat_state_unknown" }); } catch (_traceError) {} throw bridge.error("CHAT_STATE_UNKNOWN", "消息可能已经提交，但当前无法确认最终执行状态", false); } throw normalized; } }
    return { attach, request, get, close, waitForContent };
  };
})(globalThis);
