const assert = require("node:assert/strict");
const { FakeNode, loadContentRuntime } = require("./helpers");
async function scenario({ replace = false, markerDelay = null, assistant = true }) {
  const users = []; const assistants = []; let generating = false; let marker; const prompt = new FakeNode("prompt"); const button = new FakeNode("button"); const stop = new FakeNode("stop", { "data-testid": "stop-button" }); const body = new FakeNode("body");
  button.click = () => { users.push(new FakeNode("user", { "data-message-author-role": "user" }, "问题")); generating = true; if (!assistant) return; const first = new FakeNode("assistant", { "data-message-author-role": "assistant" }, "这是一个"); assistants.push(first); setTimeout(() => { generating = false; }, 20); setTimeout(() => { const final = new FakeNode("assistant", { "data-message-author-role": "assistant" }, "这是一个完整项目"); if (replace) assistants.splice(0, 1, final); else { first.innerText = first.textContent = final.innerText; } }, 70); if (markerDelay !== null) setTimeout(() => { marker = new FakeNode("marker", { "data-testid": "message-actions-copy" }); for (const node of assistants) node.marker = marker; }, markerDelay); };
  const all = () => [body, prompt, button, ...(generating ? [stop] : []), ...users, ...assistants, ...(marker ? [marker] : [])]; const document = { body, scrollingElement: body, querySelector(selector) { return this.querySelectorAll(selector)[0] || null; }, querySelectorAll(selector) { if (selector.includes('="user"')) return users; if (selector.includes('="assistant"')) return assistants; return all().filter((node) => node.matches(selector)); }, execCommand: () => false };
  const { listeners } = loadContentRuntime({ document, timingOverrides: { completionConfirmationMs: 90, responseIdleTimeoutMs: 180 } }); const response = await new Promise((resolve) => listeners[0]({ method: "chat", text: "问题", request_id: "stream" }, {}, resolve)); if (!assistant) { assert.equal(response.ok, false); assert.equal(response.error.code, "RESPONSE_TIMEOUT"); return; } assert.equal(response.ok, true); assert.equal(response.result.text, "这是一个完整项目");
}
(async () => { await scenario({}); await scenario({ replace: true }); await scenario({ markerDelay: 80 }); await scenario({ assistant: false }); })().catch((error) => { console.error(error); process.exitCode = 1; });
